<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up():void{
  Schema::create('users',function(Blueprint $t){$t->id();$t->string('name');$t->string('email')->unique();$t->timestamp('email_verified_at')->nullable();$t->string('password');$t->enum('role',['admin','manager','staff','viewer'])->default('staff');$t->boolean('is_active')->default(true);$t->rememberToken();$t->timestamps();});
  Schema::create('password_reset_tokens',function(Blueprint $t){$t->string('email')->primary();$t->string('token');$t->timestamp('created_at')->nullable();});
  Schema::create('personal_access_tokens',function(Blueprint $t){$t->id();$t->morphs('tokenable');$t->text('name');$t->string('token',64)->unique();$t->text('abilities')->nullable();$t->timestamp('last_used_at')->nullable();$t->timestamp('expires_at')->nullable()->index();$t->timestamps();});
  Schema::create('warehouses',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name',120);$t->string('address')->nullable();$t->string('phone',30)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('categories',function(Blueprint $t){$t->id();$t->string('name',120)->unique();$t->text('description')->nullable();$t->timestamps();});
  Schema::create('suppliers',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name',160);$t->string('contact_name',120)->nullable();$t->string('email')->nullable();$t->string('phone',30)->nullable();$t->string('address')->nullable();$t->string('tax_code',50)->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('customers',function(Blueprint $t){$t->id();$t->string('code',30)->unique();$t->string('name',160);$t->string('email')->nullable();$t->string('phone',30)->nullable();$t->string('address')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();});
  Schema::create('products',function(Blueprint $t){$t->id();$t->string('sku',60)->unique();$t->string('barcode',100)->nullable()->unique();$t->string('name',180);$t->foreignId('category_id')->nullable()->constrained()->nullOnDelete();$t->string('unit',30)->default('piece');$t->decimal('cost_price',15,2)->default(0);$t->decimal('selling_price',15,2)->default(0);$t->decimal('min_stock',15,3)->default(0);$t->text('description')->nullable();$t->boolean('is_active')->default(true);$t->timestamps();$t->index(['name','is_active']);});
  Schema::create('stocks',function(Blueprint $t){$t->id();$t->foreignId('warehouse_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained()->cascadeOnDelete();$t->decimal('quantity',15,3)->default(0);$t->decimal('avg_cost',15,2)->default(0);$t->timestamps();$t->unique(['warehouse_id','product_id']);});
  Schema::create('purchase_orders',function(Blueprint $t){$t->id();$t->string('po_number',60)->unique();$t->foreignId('supplier_id')->constrained();$t->foreignId('warehouse_id')->constrained();$t->enum('status',['DRAFT','ORDERED','PARTIAL','RECEIVED','CANCELLED'])->default('DRAFT');$t->date('ordered_at');$t->date('expected_at')->nullable();$t->text('notes')->nullable();$t->foreignId('created_by')->constrained('users');$t->timestamps();});
  Schema::create('purchase_order_items',function(Blueprint $t){$t->id();$t->foreignId('purchase_order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->decimal('quantity',15,3);$t->decimal('received_quantity',15,3)->default(0);$t->decimal('unit_cost',15,2);$t->timestamps();$t->unique(['purchase_order_id','product_id']);});
  Schema::create('sales_orders',function(Blueprint $t){$t->id();$t->string('so_number',60)->unique();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('warehouse_id')->constrained();$t->enum('status',['DRAFT','CONFIRMED','PARTIAL','COMPLETED','CANCELLED'])->default('DRAFT');$t->date('ordered_at');$t->text('notes')->nullable();$t->foreignId('created_by')->constrained('users');$t->timestamps();});
  Schema::create('sales_order_items',function(Blueprint $t){$t->id();$t->foreignId('sales_order_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->decimal('quantity',15,3);$t->decimal('issued_quantity',15,3)->default(0);$t->decimal('unit_price',15,2);$t->timestamps();$t->unique(['sales_order_id','product_id']);});
  Schema::create('stock_transfers',function(Blueprint $t){$t->id();$t->string('transfer_number',60)->unique();$t->foreignId('from_warehouse_id')->constrained('warehouses');$t->foreignId('to_warehouse_id')->constrained('warehouses');$t->enum('status',['DRAFT','COMPLETED','CANCELLED'])->default('DRAFT');$t->text('notes')->nullable();$t->foreignId('created_by')->constrained('users');$t->timestamp('completed_at')->nullable();$t->timestamps();});
  Schema::create('stock_transfer_items',function(Blueprint $t){$t->id();$t->foreignId('stock_transfer_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->decimal('quantity',15,3);$t->timestamps();$t->unique(['stock_transfer_id','product_id']);});
  Schema::create('stock_counts',function(Blueprint $t){$t->id();$t->string('count_number',60)->unique();$t->foreignId('warehouse_id')->constrained();$t->enum('status',['DRAFT','FINALIZED'])->default('DRAFT');$t->text('notes')->nullable();$t->foreignId('created_by')->constrained('users');$t->timestamp('finalized_at')->nullable();$t->timestamps();});
  Schema::create('stock_count_items',function(Blueprint $t){$t->id();$t->foreignId('stock_count_id')->constrained()->cascadeOnDelete();$t->foreignId('product_id')->constrained();$t->decimal('system_quantity',15,3);$t->decimal('counted_quantity',15,3);$t->decimal('difference',15,3)->default(0);$t->timestamps();$t->unique(['stock_count_id','product_id']);});
  Schema::create('stock_movements',function(Blueprint $t){$t->id();$t->foreignId('warehouse_id')->constrained();$t->foreignId('product_id')->constrained();$t->enum('type',['IN','OUT','TRANSFER_IN','TRANSFER_OUT','ADJUSTMENT_POSITIVE','ADJUSTMENT_NEGATIVE']);$t->decimal('quantity',15,3);$t->decimal('unit_cost',15,2)->default(0);$t->string('reference_type',40);$t->unsignedBigInteger('reference_id');$t->string('note')->nullable();$t->foreignId('performed_by')->constrained('users');$t->timestamp('occurred_at')->useCurrent();$t->index(['product_id','warehouse_id','occurred_at']);$t->index(['reference_type','reference_id']);});
  Schema::create('jobs',function(Blueprint $t){$t->bigIncrements('id');$t->string('queue')->index();$t->longText('payload');$t->unsignedTinyInteger('attempts');$t->unsignedInteger('reserved_at')->nullable();$t->unsignedInteger('available_at');$t->unsignedInteger('created_at');});
  Schema::create('failed_jobs',function(Blueprint $t){$t->id();$t->string('uuid')->unique();$t->text('connection');$t->text('queue');$t->longText('payload');$t->longText('exception');$t->timestamp('failed_at')->useCurrent();});
 }
 public function down():void{foreach(['failed_jobs','jobs','stock_movements','stock_count_items','stock_counts','stock_transfer_items','stock_transfers','sales_order_items','sales_orders','purchase_order_items','purchase_orders','stocks','products','customers','suppliers','categories','warehouses','personal_access_tokens','password_reset_tokens','users'] as $t)Schema::dropIfExists($t);}
};
